### ISSUE TITLE
GSpine animation playback is missing parameters

### ISSUE THREAD

**Issue by MartinSenovsky** [pshtif/Genome2D-Spine#2]
Genome2D-Spine/src/com/genome2d/components/renderable/GSpine.hx

Change function:
public function setActiveSkeleton(p_skeletonId:String, p_anim:String):Void 

to not play animation and 
add function to actually play animations with loop option like:

public function playAnimation(layerIndex:int, animationId:String, loop:Bool):Void

**Comment by pshtif** [comment]
Added changes and split GSpine to:

GSpine - Its a separate Spine renderer not bound to node/component
GSpineComponent - Its a component wrapper to render spine on node graph
GUISpineSkin - Its a ui skin wrapper to render spine in ui
